[workspace]
resolver = "3"
members = ["strands-metrics", "strands-rs", "filament-sys", "helix"]
default-members = ["strands-metrics"]

[workspace.dependencies]
filament-sys = { path = "filament-sys" }
